packages/auth-provider/project.json

What happend
* publib-npm was not called during release
* nx release does not support bundled dependencies https://github.com/nrwl/nx/issues/21789
Fix:
replace `nx-release-publish` command with `publib-npm` call which supports bundled dependencies

 fix: no bundled dependencies in auth-provider package

---

.github/workflows/nx-release.yaml

publib npm expects different name for NPM_TOKEN env variable

fix: allow publib consume npm token

---

packages/auth-provider/project.json

node_modules has to be installed in package folder for publish process to pick-up them

fix(auth-provider): install deps before build

---

packages/auth-provider/README.md

PAT publicKey is not needed for TDK AuthProvider initialization.

docs: remove redundant variable from class initialization in readme

---

package-lock.json
packages/auth-provider/helpers/jwt.ts
packages/auth-provider/package.json

<details><summary>Click to show testing of expiration screenshot</summary>
</details>
NOTE: 
- consider replacing jsonwebtoken with jose in jwt helper of AuthProvider package

feat: FTL-15689 use jose to get pem from jwk, since it has no issues in nextjs

---

.github/workflows/nx-release.yaml
libs/iota-core/README.md
libs/iota-core/package.json
libs/iota-core/project.json
packages/auth-provider/README.md
packages/auth-provider/package.json
packages/auth-provider/project.json
packages/common/README.md
packages/common/package.json
packages/common/project.json

1) enables releases of jsii packages to pypi:
* auth-provider
* common
* iota-core
2) documentation updated
3) package names for python fixed. (underscores are not supported in package name)
4) pypi trusted publisher(oidc auth) is used to release packages to pypi

feat(python): enable publishing of jsii packages to pypi

---

.github/workflows/nx-release.yaml

fixes issue when publishing process is not picking up last commit done by release job.

fix: publish process - always pick last commit

---

.eslintrc.json
.github/workflows/nx-branch.yaml
.github/workflows/nx-release.yaml
clients/python/iam_client/project.json
clients/python/iam_client/pyproject.toml
nx.json
package-lock.json
package.json
tools/nx-tdk-tools/.eslintrc.json
tools/nx-tdk-tools/README.md
tools/nx-tdk-tools/executors.json
tools/nx-tdk-tools/package.json
tools/nx-tdk-tools/project.json
tools/nx-tdk-tools/src/executors/set-version/executor.ts
tools/nx-tdk-tools/src/executors/set-version/schema.d.ts
tools/nx-tdk-tools/src/executors/set-version/schema.json
tools/nx-tdk-tools/tsconfig.json
tools/nx-tdk-tools/tsconfig.lib.json
tools/nx-tdk-tools/tsconfig.spec.json
tsconfig.base.json

* releases for python clients to pypi
* versioning of python clients is synchronised to nodejs client versions
* added nx tdk plugin with set version executor

feat: python client package releases

---

.github/workflows/nx-branch.yaml
.husky/commit-msg
package-lock.json

Fix swc compiler issue when running custom executor by resetting projects package-lock.json (as suggested by nx)
```
NX   invalid type: unit value, expected struct Options
Error: invalid type: unit value, expected struct Options
at module.exports.__wbindgen_error_new (/home/runner/work/affinidi-tdk/affinidi-tdk/node_modules/@swc/wasm/wasm.js:552:17)
at ***.<anonymous> (wasm://wasm/053083e6:1:15562816)
at ***.<anonymous> (wasm://wasm/053083e6:1:16458264)
at ***.<anonymous> (wasm://wasm/053083e6:1:16614049)
at ***.<anonymous> (wasm://wasm/053083e6:1:5423603)
at ***.<anonymous> (wasm://wasm/053083e6:1:3147300)
at ***.<anonymous> (wasm://wasm/053083e6:1:12769742)
at ***.<anonymous> (wasm://wasm/053083e6:1:1487331)
at ***.<anonymous> (wasm://wasm/053083e6:1:2844031)
at ***.<anonymous> …
```

Fix: executor compile issue

---

packages/auth-provider/auth-provider.ts

Use `apiGatewayUrl` as a parameter name.

fix: revert parameter name

---

.nxignore

fixes issue with over releeasing empty changes of libraries

fix: avoid empty releases by ignoring package.lock.json

---

scripts/generate_dart_codes.sh

To generate in `./clients/dart`, no params:
```
sh ./scripts/generate_dart_codes.sh
```
To generate in `./packages/dart`, add params:
```
sh ./scripts/generate_dart_codes.sh ./packages/dart
```

feat: add script to generate dart code

---

.github/workflows/nx-release.yaml

* make sure requirements met to release java & python from semantic-release target
* remove old security pipeline
* jsii packages for python are still released from publish step, as well as any js package

fix: release java & python on semantic release step

---

packages/java/auth.provider/pom.xml
packages/java/auth.provider/project.json
packages/java/common/pom.xml
packages/java/common/project.json

* adds auth and common package to build pipeline
* adds releases & publish nx pipeline
* adds publishing config to maven pom xml's
nx  `project.json` file is added, so this projects could be discovered by nx and their targets included when gh workflow calls them
semantic release sets version for both packages.
issue with auth provider being dependant on common package is handled by adding common package as implicit depenency in auth package as well as using `install` target
maven targets are called from nx targets

feat: java packages publishing

---

.github/workflows/nx-release.yaml

passing  oidc token was left out

fix: python package publishing

---

.github/workflows/nx-release.yaml
libs/iota-browser/package.json
libs/iota-browser/project.json
libs/iota-core/package.json
libs/iota-core/project.json
package.json
packages/jsii/auth-provider/package.json
packages/jsii/auth-provider/project.json
packages/jsii/common/package.json
packages/jsii/common/project.json

* makes sure packages are recognised as  public
* semantic release exec plugin to release
* aligned to clients
* fixed issue with path to nx projects in new jsii folder

fix: publish ts & jsii via semantic release

---

.github/workflows/publish-dart.yaml
package-lock.json
packages/dart/auth_provider/project.json
packages/dart/common/project.json
packages/dart/consumer_auth_provider/project.json
packages/dart/cryptography/project.json

Because pub.dev only allows publishing from tags we need a separate workflow to do the publishing. Also tag pattern is pretty strict, nx project naming should be changed accordingly. Generated clients will follow once packages are done.

feat: add dart publishing on tags

---

libs/dart/iota_core/.env.example
libs/dart/iota_core/.gitignore
libs/dart/iota_core/CHANGELOG.md
libs/dart/iota_core/README.md
libs/dart/iota_core/example/main.dart
libs/dart/iota_core/lib/affinidi_tdk_iota_core.dart
libs/dart/iota_core/lib/src/iota_auth_provider.dart
libs/dart/iota_core/pubspec.yaml
libs/dart/iota_core/test/iota_core_test.dart
pubspec.yaml
tests/integration/dart/pubspec.yaml
tests/integration/dart/test/environment.dart
tests/integration/dart/test/iota_client_test.dart

Added core-library to generate the Iota Credentials required for init of the WebSocket data-sharing mode.

feat: add iota-core library

---

packages/dart/common/lib/src/environment.dart

To ensure that String.fromEnvironment("") works with compiled code we need to define it as a const.
Note that with this change it is now important to specify the file name when running just in time: 
`dart run --define=AFFINIDI_TDK_ENVIRONMENT=dev bin/vfs_access_control.dart`

fix: fetch correct environment on compile

---

.github/workflows/publish-dart.yaml
packages/dart/auth_provider/project.json
packages/dart/common/project.json
packages/dart/consumer_auth_provider/project.json
packages/dart/cryptography/project.json

* allows manually start dart publishing
* disable git plugin for now to unblock automatic releases

fix: dart publishing

---

libs/dart/vault/example/main.dart
libs/dart/vault/example/shared_profiles.dart
libs/dart/vault_storages/lib/src/profiles/vfs_profile_repository.dart

* clears memoized data associated to profiles when deleting profile to prevent reuse.
* clears credentials on existing profiles when resetting examples
* clears subfolders on existing profiles when resetting examples

fix: clear memoized profile data on profile deletion

---

libs/dart/claim_verifiable_credential/lib/src/exceptions/tdk_exception_type.dart
libs/dart/claim_verifiable_credential/lib/src/oid4vci_claim_verifiable_credential.dart
libs/dart/claim_verifiable_credential/test/claim_verifiable_credential_test.dart

Inverted order of network requests.
It now first checks for issuer metadata and if this can be parsed continues to make a credential offer request.
If the metadata retrieved does not match the expected data format, it will throw an error with code failedToLoadIssuerMetadata

chore: request credential offer issuer metadata before the offer

---

libs/dart/vault/example/main.dart
libs/dart/vault/lib/src/storage_interfaces/vault_store.dart
libs/dart/vault/lib/src/vault.dart
libs/dart/vault_flutter_utils/example/flutter_secure_storage/lib/services/vault_service.dart

* changed getRandomSeed to use 32 bytes instead of 16
* removed code to initialize a vault from seed, developers can initialize vault from VaultStore and achieve the same

fix: changed getRandomSeed to use 32 bytes 

---

packages/dart/vault_edge_drift_provider/example/pubspec.yaml
tests/integration/dart/test/helpers/environment.dart
tests/integration/dart/test/helpers/resource_factory.dart
tests/integration/dart/test/wallets_client_test.dart

* Override `clock` dependency with version `1.1.1` because `dart_jsonwebtoken` depends on `clock ^1.1.2` 
* Removed unused an unnecessary imports from integration tests
* Renamed variable in integration tests to use loweredCamelCase convention

chore: override clock dependency on example project

---

packages/jsii/auth-provider/package-lock.json
packages/jsii/auth-provider/package.json
packages/jsii/common/package-lock.json
packages/jsii/common/package.json

Bumping to the latest version due to version below 5.7.x stopped being supported (see [repo's Maintenance & Support section](https://github.com/aws/jsii-compiler/blob/be96253bc138efbbe44586f937f2485a057fb0cd/README.md#gear-maintenance--support)).

chore: bump jsii dependency
