affinidi/affinidi-tdk

- package-lock.json
- packages/common/.eslintrc.json
- packages/common/.gitignore
- packages/common/.npmignore
- packages/common/README.md
- packages/common/helpers/environment.ts
- packages/common/helpers/index.ts
- packages/common/helpers/logger.ts
- packages/common/helpers/vault.ts
- packages/common/index.ts
- packages/common/package-lock.json
- packages/common/package.json
- packages/common/project.json
Adds:
- URL resolving based on environment
- Vault link builders
- Simple logger
> feat: common package

- .github/workflows/auto-pr.yaml
When "feat/update-client...." branch is created, PR will be raised automatically
> feat: automatically open mr on client updates

- .github/workflows/nx-release.yaml
Fixes issue when jsii-rosetta not found during packaging https://github.com/affinidi/affinidi-tdk/actions/runs/10348202557/job/28640254350#step:9:161
> fix: fix dependency issues by moving semantic release up

- .github/workflows/nx-release.yaml
fixes ci issue https://github.com/affinidi/affinidi-tdk/actions/runs/10351433597/job/28650256967
> fix: semantic-release

- README.md
- libs/iota-core/README.md
- Updated main readme file for supported modules
- Updated Docs link and pip install for iota-core
> fix: updated readme details

- .github/workflows/nx-release.yaml
* decouple release and publish jobs to have reliable results
* define strong needs before security release and publish
> fix: decouple release and publish

- README.md
- Fixed links.
- Updated content in the Documentation section, adding links to the Docs site.
> docs: updated readme and fixes links

- nx.json
release all packages, not only js ones. ref: https://github.com/nrwl/nx/issues/23439#issuecomment-2158452232
> fix: release non js packages by default

- .github/dependabot.yaml
- .github/workflows/nx-branch.yaml
- nx.json
* disable inderect dependency detection and package.json detection (only implicit  dependecies will be taken care of) ref: https://github.com/nrwl/nx/issues/15116
* remove security pipeline, as it does not do anything usefull
* enable dependabot for python/dart
> fix: pipeline improvments

- .github/workflows/nx-release.yaml
fixes https://github.com/affinidi/affinidi-tdk/actions/runs/11103281212/job/30857090784#step:10:161
> fix: race on release build

- package-lock.json
- package.json
This reverts commit 26f4f8740866a74496f1539787ee19cc10924599.
> revert: bump @semantic-release/npm -> npm (#284)

- README.md
Additions:
- Added PHP to the list of supported languages.
> docs: updated supported language list

- README.md
- packages/java/auth.provider/.env.example
- packages/java/auth.provider/README.md
Updates:
- Updated main readme to add support for Java.
- Updated Auth.Provider package readme.
> docs: updated readme for Java

- packages/java/auth.provider/pom.xml
- packages/java/auth.provider/project.json
- packages/java/common/pom.xml
- packages/java/common/project.json
fixes https://github.com/affinidi/affinidi-tdk/actions/runs/12910563488/job/36001370557#step:12:232
> fix: deploy target execution issue

- packages/dart/auth_provider/.pubignore
- packages/dart/auth_provider/LICENSE
- packages/dart/auth_provider/project.json
- packages/dart/common/.pubignore
- packages/dart/common/LICENSE
- packages/dart/common/analysis_options.yaml
- packages/dart/common/project.json
- packages/dart/consumer_auth_provider/.pubignore
- packages/dart/consumer_auth_provider/LICENSE
- packages/dart/consumer_auth_provider/project.json
- packages/dart/cryptography/.pubignore
- packages/dart/cryptography/LICENSE
- packages/dart/cryptography/project.json
Prepare packages for publishing:
- add LICENCE files
- Add configuration for NX
- Add pubignore files
> feat: add package publishing

- packages/dart/auth_provider/project.json
- packages/dart/common/project.json
- packages/dart/consumer_auth_provider/project.json
- packages/dart/cryptography/project.json
> fix: package json

- .github/workflows/publish-dart.yaml
fix passing args to the underlying command
> fix: nx parameters

- .github/workflows/publish-dart.yaml
- packages/dart/auth_provider/project.json
- packages/dart/common/project.json
- packages/dart/consumer_auth_provider/project.json
- packages/dart/cryptography/project.json
fix: avoid passing argument to publish command
> fix: use environment variables in NX

- packages/dart/auth_provider/project.json
- packages/dart/common/project.json
- packages/dart/consumer_auth_provider/project.json
- packages/dart/cryptography/project.json
fix: removing test script from project.json
> fix: remove test script

- packages/dart/common/project.json
fix: version substitution command
> fix: version substitution

- packages/dart/consumer_auth_provider/project.json
fix version substitution command
> fix: version substitution for consumer auth provider

- packages/dart/cryptography/pubspec.yaml
fix: align cryptography pubspec with pub.dev project
> fix: match pubspec with pubdev

- packages/dart/cryptography/project.json
- packages/dart/cryptography/pubspec.yaml
fix: cryptography package name
> fix: cryptography package name

- packages/dart/auth_provider/project.json
- packages/dart/common/project.json
- packages/dart/consumer_auth_provider/project.json
- packages/dart/cryptography/project.json
* enabled changelog generation from commits
* enabled commiting changelog to repo
> ci: commit changelog in dart

- .github/workflows/nx-release.yaml
> ci: fix java releases

- .github/workflows/nx-release.yaml
> fix: python release tool version typo

- packages/dart/common/lib/src/environment.dart
- packages/dart/common/lib/src/vault_utils.dart
- packages/dart/common/test/common_test.dart
Allow to get vaultUrl from VaultUtils.
> feat: add elementsVaultApiUrl to environment

- packages/dart/common/lib/src/environment.dart
- packages/dart/common/test/common_test.dart
- tests/integration/dart/test/elements_public_key_test.dart
* allow to select the region used to resolve URLs in common package
* expose JWT audience URL for accounts endpoint
> feat: support region through common package

- .github/workflows/nx-branch.yaml
- .github/workflows/publish-dart.yaml
* make sure we authorize in pub.dev before publishing (flutter sdk action requires additional action)
* add caching of deps and sdk's
> fix: dart publishing

- libs/dart/iota_core/example/main.dart
- packages/dart/auth_provider/lib/src/jwt_helper.dart
- tests/integration/dart/test/iota_client_test.dart
- tests/integration/dart/test/login_configuration_client_test.dart
- tests/integration/dart/test/login_configuration_client_user_groups_test.dart
- tests/integration/dart/test/verification_client_test.dart
- tests/integration/dart/test/wallets_client_test.dart
* add missing await on expectLater
* removed warnings for unused_local_variable
* removed warnings for unused_import
* removed warnings for invalid_null_aware_operator
* removed warnings for unnecessary_non_null_assertion
> chore: removed linter warnings

- tests/integration/dart/test/environment.dart
- tests/integration/dart/test/iam_client_test.dart
- tests/integration/dart/test/verification_client_test.dart
* enable tests for dart verification client
* minor formatting changes (via `dart format .`)
NOTE: VC objects will be extracted into fixtures in a separate PR.
> test: enable tests for dart verification client

- libs/dart/claim_verifiable_credential/pubspec.yaml
- libs/dart/iota_core/pubspec.yaml
- libs/dart/vault/pubspec.yaml
- libs/dart/vault_storages/pubspec.yaml
- packages/dart/auth_provider/pubspec.yaml
- packages/dart/common/example/pubspec.yaml
- packages/dart/consumer_auth_provider/example/pubspec.yaml
- packages/dart/consumer_auth_provider/pubspec.yaml
- packages/dart/vault_data_manager/pubspec.yaml
Update all Affinidi packages to use the latest Affinidi package versions
> fix: update package dependencies

- packages/jsii/auth-provider/package-lock.json
- tests/integration/python/credential_issuance_client_test.py
fix for axios, cross-spawn dependencies
> fix: npm vulnerabilities

- packages/jsii/auth-provider/package-lock.json
- packages/jsii/auth-provider/package.json
fixes https://github.com/advisories/GHSA-fjxv-7rqg-78g4
> fix: bump axios dependency
